name: CI Workflow

on:
  push:
    branches: ["main"]

permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.7"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow

    - name: Run mlflow project
      run: |
        mlflow run MLProject --env-manager=local

    - name: Get latest MLflow run_id
      run: |
        RUN_ID=$(ls -td mlruns/0/*/ | grep -Eo '[0-9a-f]{32}' | head -n 1)
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
        echo "Latest run_id: $RUN_ID"

    - name: Commit & Push results
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add mlruns/
        git commit -m "Upload artifact [skip ci]" || echo "No changes to commit"
        git push origin main

    - name: Build Docker Model
      run: |
        mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "insurance_model" 

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Tag Docker Image
      run: |
        docker tag insurance_model ${{ secrets.DOCKER_HUB_USERNAME }}/insurance_model:latest
        
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/insurance_model:latest
